Document: sambaedu-config
Title: Debian sambaedu-config Manual
Author: <insert document author here>
Abstract: This manual describes what sambaedu-config is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sambaedu-config/sambaedu-config.sgml.gz

Format: postscript
Files: /usr/share/doc/sambaedu-config/sambaedu-config.ps.gz

Format: text
Files: /usr/share/doc/sambaedu-config/sambaedu-config.text.gz

Format: HTML
Index: /usr/share/doc/sambaedu-config/html/index.html
Files: /usr/share/doc/sambaedu-config/html/*.html
